### ISSUE TITLE
Mexa64-file ccg 

### ISSUE THREAD

**Issue by michaelhadler** [nsteinme/steinmetz-et-al-2019#4]
Hi,

tried to run ccg_mine from Matlab 2020 on Ubuntu 18.04. Got following Error:

Invalid MEX-file '/home/michael/Documents/MATLAB/spikes-master/analysis/helpers/CCGHeart.mexa64':
/home/michael/Documents/MATLAB/spikes-master/analysis/helpers/CCGHeart.mexa64: undefined symbol: mxErrMsgTxt

I didn't look into the mex-file yet (beginner, sorry) but from the looks of it: On one occasion mxErrMsgTxt still needs to be commented out (or deleted altogether) and replaced by mexErrMsgIdAndTxt

Best,

Michael

**Comment by nsteinme** [comment]
Could you try to replace it with the equivalent files from here?
https://github.com/cortex-lab/spikes/tree/master/analysis/helpers

I think those might have been updated? I know I did this once... :)

**Comment by michaelhadler** [comment]
Hey,
the spikes master is where I got the file from in the first place, I guess I landed on your page from the comment section ^^ What platform did you use it on?

**Comment by nsteinme** [comment]
Sorry for being slow. Ok I see the problem - the c file is corrected, and
it has been re-compiled on mac and windows, but it needs someone to compile
it on linux in order to update the .mexa64 version. So you need to compile
it, which means called "mex CCGHeart" and following any instructions you
get if it doesn't work. I'm going to close the issue here - please open a
new issue at the spikes repo if you still have problems. And btw if you
want to make a PR to the spikes repo with your new compiled version, I'm
sure others would find that helpful. Thanks and good luck -
